version: "3.1"

# Used by user-office-develop to be able to run every components
services:
  scheduler-backend:
    image: "dmsc/duo-scheduler-backend:${USER_OFFICE_SCHEDULER_BACKEND_TAG}"
    environment:
      NODE_ENV: development
      DATABASE_HOSTNAME: scheduler-db
      DATABASE_PORT: 5432
      DATABASE_USER: schedulerUser
      DATABASE_PASSWORD: schedulerPassword
      DATABASE_DATABASE: scheduler
      SCHEDULER_CONFIG_AUTH_REDIRECT: /not-authenticated#USER_OFFICE/shared-auth
      USER_OFFICE_ENDPOINT: ${USER_OFFICE_ENDPOINT}
      UO_FEATURE_DISABLE_MESSAGE_BROKER: 1
      SKIP_DB_INIT: 1
    depends_on:
      - scheduler-db

  scheduler-db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: schedulerUser
      POSTGRES_PASSWORD: schedulerPassword
    ports:
      - 5432
    volumes:
      - "./${USER_OFFICE_SCHEDULER_BACKEND_DIR}/db_patches/:/docker-entrypoint-initdb.d/"
