version: "3.1"

services:
  scheduler-proxy:
    image: traefik:1.7 # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80" # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
  services:
  duo-cron-job:
    image: dmsc/duo-cron-job:develop
    environment:
      API_URL: http://host.docker.internal:4000/graphql
      API_AUTH_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJ1c2VyX3RpdGxlIjoiTXIuIiwiZmlyc3RuYW1lIjoiQW5kZXJzIiwibWlkZGxlbmFtZSI6IkFkYW0iLCJsYXN0bmFtZSI6IkFuZGVyc3NvbiIsInVzZXJuYW1lIjoidGVzdG9mZmljZXIiLCJwcmVmZXJyZWRuYW1lIjoiUmhpYW5ub24iLCJvcmNpZCI6Ijg3ODMyMTg5NyIsImdlbmRlciI6Im1hbGUiLCJuYXRpb25hbGl0eSI6IkZyZW5jaCIsImJpcnRoZGF0ZSI6IjE5ODEtMDgtMDRUMjI6MDA6MDAuMDAwWiIsIm9yZ2FuaXNhdGlvbiI6IlBmYW5uZXJzdGlsbCBhbmQgU29ucyIsImRlcGFydG1lbnQiOiJJVCBkZXBhcnRtZW50Iiwib3JnYW5pc2F0aW9uX2FkZHJlc3MiOiJDb25nbywgQWxsZW5ldmlsbGUsIDM1ODIzIE11ZWxsZXIgR2xlbnMiLCJwb3NpdGlvbiI6IkxpYWlzb24iLCJlbWFpbCI6IkFhcm9uX0hhcnJpczQ5QGdtYWlsLmNvbSIsImVtYWlsVmVyaWZpZWQiOnRydWUsInRlbGVwaG9uZSI6IjcxMS0zMTYtNTcyOCIsInRlbGVwaG9uZV9hbHQiOiIxLTM1OS04NjQtMzQ4OSB4NzM5MCIsImNyZWF0ZWQiOiIyMDE5LTEwLTE3VDEwOjU4OjM4LjczNVoiLCJ1cGRhdGVkIjoiMjAxOS0xMC0xN1QxMDo1ODozOC43MzVaIn0sInJvbGVzIjpbeyJpZCI6Miwic2hvcnRDb2RlIjoidXNlcl9vZmZpY2VyIiwidGl0bGUiOiJVc2VyIE9mZmljZXIifV0sImlhdCI6MTU3MTMyNzQ2Mn0.NinmUuwuu0D6syqwd2z5J1BaqhwRPlFaxtML8sA2Ang

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: duopassword
      POSTGRES_USER: duouser
      POSTGRES_DB: duo
    ports:
      - 5432:5432
    volumes:
      - "${USER_OFFICE_BACKEND_DIR}/db_patches/:/docker-entrypoint-initdb.d/"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "${USER_OFFICE_BACKEND_DIR}/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config"

  factory:
    image: dmsc/duo-factory:${USER_OFFICE_FACTORY_TAG}
    init: true
    environment:
      NODE_ENV: development
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      DATABASE_USER: duouser
      DATABASE_PASSWORD: duopassword
      DATABASE_DATABASE: duo
    ports:
      - 4500:4500
    cap_add:
      - SYS_ADMIN

  backend:
    image: "dmsc/duo-backend:${USER_OFFICE_BACKEND_TAG}"
    environment:
      DATABASE_URL: postgres://duouser:duopassword@db:5432/duo
      secret: qMyLZALzs229ybdQXNyzYRdju7X784TH
      tokenLife: 7d
      baseURL: localhost:3000
      SPARKPOST_TOKEN: dummytoken
      NODE_ENV: development
      DEPENDENCY_CONFIG: e2e
      USER_OFFICE_FACTORY_ENDPOINT: ${USER_OFFICE_FACTORY_ENDPOINT}
      TZ: Europe/Stockholm
      DATE_FORMAT: dd-MM-yyyy
      DATE_TIME_FORMAT: dd-MM-yyyy HH:mm
      EMAIL_AS_EXTERNAL_TOKEN_AUTHORIZATION: "true"
    labels:
      - "traefik.frontend.rule=PathPrefix:/api, /downloads, /files, /download, /uploads"
      - "traefik.port=4000"
    volumes:
      - "${USER_OFFICE_BACKEND_DIR}/db_patches:/home/node/app/db_patches"
      
  scheduler-frontend:
    image: "duo-scheduler-frontend:${BUILD_TAG}"
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.port=80"
    depends_on:
      - gateway

  cypress:
    image: e2e-cypress:latest
    ipc: host # see https://github.com/cypress-io/cypress/issues/350
    environment:
      CYPRESS_SVC_ACC_TOKEN: $SVC_ACC_TOKEN
    entrypoint:
      ["/wait-for-frontend.sh", "scheduler-frontend:80", "npm run cy:run"]
    depends_on:
      - scheduler-frontend
    volumes:
      - "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress/screenshots:/tmp/screenshots"
      - "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress/fixtures:/e2e/cypress/fixtures"
      - "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress/integration:/e2e/cypress/integration"
      - "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress/plugins:/e2e/cypress/plugins"
      - "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress/support:/e2e/cypress/support"
