version: "3.1"

# Used by user-office-develop to be able to run every components
services:
  scheduler-backend:
    image: "dmsc/duo-scheduler-backend:${USER_OFFICE_SCHEDULER_BACKEND_TAG}"
    environment:
      - NODE_ENV=production
      - DATABASE_HOSTNAME=scheduler-db
      - DATABASE_PORT=5432
      - DATABASE_USER=schedulerUser
      - DATABASE_PASSWORD=schedulerPassword
      - DATABASE_DATABASE=scheduler
    depends_on:
      - scheduler-db

  scheduler-db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: schedulerUser
      POSTGRES_PASSWORD: schedulerPassword
      INCLUDE_SEEDS: 1
    ports:
      - 5432
    volumes:
      - "./${USER_OFFICE_SCHEDULER_BACKEND_DIR}/db_patches/:/docker-entrypoint-initdb.d/"
